name: Run Playwright Tests - Web Main
on:
    pull_request:
        types: [opened, synchronize, reopened]
        branches:
            - main
        paths:
            - '.github/workflows/web-main.yml'
jobs:
    test_and_report:
        name: Test and Report
        environment: main
        timeout-minutes: 60
        permissions:
            pull-requests: write
            id-token: write
            contents: write
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18.x]
        env:
            CI: true
        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.pull_request.head.ref }}
            
            - name: Generate Test Reports Artifact
              uses: actions/upload-artifact@v4
              if: always()
              with:
                  name: test-report
                  path: Readme.md
                  retention-days: 1
    
    push_screenshots_on_approval:
        name: Push Screenshots On Approval
        runs-on: ubuntu-latest
        needs: test_and_report
        environment: Sandbox
        timeout-minutes: 60
        env:
            CI: true
        steps:
            - name: Download Artifact
              uses: actions/download-artifact@v4
              with:
                name: test-report
                path: ./
                
            - name: Upload Artifact on Approval
              run: |
                echo "Uploading the artifact now"
                cat Readme.md